# Jekyll configuration
title: Your Project Name
baseurl: "/code-clarity" # Should match your repository name
url: "" # Leave empty for GitHub Pages

# Build settings
markdown: kramdown
exclude:
  - node_modules
  - package.json
  - package-lock.json
  - README.md
  - .github
  - .gitignore
  - frontend/node_modules
  - frontend/src
  - frontend/public
  - backend
  
# Include the built files
include:
  - frontend/build

# Keep frontend build files unchanged
keep_files:
  - frontend/build

# Disable unnecessary plugins
plugins: []