name: Deploy Frontend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: "./frontend/package-lock.json"

      - name: Configure custom domain
        run: echo "code-clarity.insitechinternational.com" > ./frontend/public/CNAME

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build
        env:
          CI: true

      - name: Debug - List build directory
        run: ls -la build

      - name: Debug - Check index.html
        run: cat build/index.html || echo "index.html not found"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend/build
          publish_branch: gh-pages
          keep_files: true
          cname: code-clarity.insitechinternational.com
          commit_message: "Deploy: ${{ github.event.head_commit.message }}"

      - name: Debug - Check gh-pages branch
        run: |
          git fetch origin gh-pages
          git checkout gh-pages
          ls -la
