name: Deploy Frontend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: "./frontend/package-lock.json"

      - name: Install dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Build project
        working-directory: ./frontend
        run: npm run build
        env:
          CI: true
          PUBLIC_URL: "https://code-clarity.insitechinternational.com"

      - name: Debug - List build contents
        working-directory: ./frontend
        run: |
          echo "Build directory contents:"
          ls -la build/
          echo "Current working directory:"
          pwd

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend/build
          publish_branch: gh-pages
          force_orphan: true  # This ensures a clean deployment
          cname: code-clarity.insitechinternational.com
          enable_jekyll: false
          commit_message: "Deploy: ${{ github.event.head_commit.message }}"

      - name: Verify deployment
        run: |
          git fetch origin gh-pages
          git checkout gh-pages
          echo "Root directory contents:"
          ls -la
          echo "Checking for index.html:"
          [ -f "index.html" ] && echo "index.html exists" || echo "index.html missing"