name: Deploy Frontend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: "./frontend/package-lock.json"

      - name: Install dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Build project
        working-directory: ./frontend
        run: npm run build
        env:
          CI: true

      - name: Debug - Check build output
        working-directory: ./frontend
        run: |
          echo "Listing build directory contents:"
          ls -la build/
          echo "Checking for index.html:"
          cat build/index.html || echo "index.html not found"
          echo "Checking for static directory:"
          ls -la build/static || echo "static directory not found"

      - name: Create necessary files
        run: |
          echo "code-clarity.insitechinternational.com" > ./frontend/build/CNAME
          touch ./frontend/build/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend/build
          publish_branch: gh-pages
          keep_files: false
          cname: code-clarity.insitechinternational.com
          commit_message: "Deploy: ${{ github.event.head_commit.message }}"

      - name: Verify deployment files
        run: |
          git fetch origin gh-pages
          git checkout gh-pages
          echo "Contents of gh-pages branch:"
          ls -la
          echo "Checking for index.html in root:"
          cat index.html || echo "index.html not found in root"
