name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the deployment from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Specify the version you want

      - name: Install dependencies
        run: |
          cd frontend
          npm install

      - name: Build the project
        run: |
          cd frontend
          npm run build

      - name: Copy build files to docs
        run: |
          mkdir -p docs  # Ensure the docs directory exists
          cp -r frontend/build/* docs/  # Copy build files to docs

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs  # Now pointing to the docs directory
          publish_branch: gh-pages
