name: Deploy Frontend

on:
  push:
    branches:
      - main # Change this to your default branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16" # Change this to the version you are using

      - name: Install dependencies
        run: npm install
        working-directory: ./frontend # Ensure this points to your frontend directory

      - name: Build
        run: npm run build
        working-directory: ./frontend # Ensure this points to your frontend directory

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend/build # Path to the build directory
          publish_branch: gh-pages # Specify the branch for deployment
